version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db;Database=SHSchemaBuilderDb2;User Id=sa;Password=Your_password123;TrustServerCertificate=True;MultipleActiveResultSets=true
    ports:
      - "8080:8080"
    depends_on:
      - db

  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  sqlvolume:
