// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260307080035_AddTableNameFullAndSeed45")]
    partial class AddTableNameFullAndSeed45
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Server.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Server.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cardinality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCore")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentGroupId")
                        .HasColumnType("int");

                    b.Property<string>("SqlTableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableNameFull")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentGroupId");

                    b.HasIndex("TierId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cardinality = "1:N",
                            Description = "Danh mục nhóm dược lý",
                            IsCore = true,
                            Name = "Nhóm Dược Lý",
                            SqlTableName = "bnt4_nhduly",
                            TableNameFull = "nhomduocly",
                            TierId = 4
                        },
                        new
                        {
                            Id = 2,
                            Cardinality = "1:N",
                            Description = "Danh mục hoạt chất",
                            IsCore = true,
                            Name = "Hoạt Chất",
                            SqlTableName = "bnt4_hoatch",
                            TableNameFull = "hoatchat",
                            TierId = 4
                        },
                        new
                        {
                            Id = 3,
                            Cardinality = "1:N",
                            Description = "Quy tắc dị ứng chéo",
                            IsCore = true,
                            Name = "Dị ứng Chéo",
                            SqlTableName = "bnt4_ducheo",
                            TableNameFull = "diungcheo",
                            TierId = 4
                        },
                        new
                        {
                            Id = 4,
                            Cardinality = "1:N",
                            Description = "Tương tác giữa các hoạt chất",
                            IsCore = true,
                            Name = "Tương Tác Thuốc",
                            SqlTableName = "bnt4_tuatac",
                            TableNameFull = "tuongtacthuoc",
                            TierId = 4
                        },
                        new
                        {
                            Id = 5,
                            Cardinality = "1:N",
                            Description = "Hồ sơ dị ứng của bệnh nhân",
                            IsCore = true,
                            Name = "Dị Ứng Bệnh Nhân",
                            SqlTableName = "bnt4_diungb",
                            TableNameFull = "diungbenhnhan",
                            TierId = 4
                        },
                        new
                        {
                            Id = 6,
                            Cardinality = "1:N",
                            Description = "Bệnh lý nền bất biến",
                            IsCore = true,
                            Name = "Bệnh Nền",
                            SqlTableName = "bnt4_bnenan",
                            TableNameFull = "benhnen",
                            TierId = 4
                        },
                        new
                        {
                            Id = 7,
                            Cardinality = "1:N",
                            Description = "Bộ quy tắc cảnh báo lâm sàng",
                            IsCore = true,
                            Name = "Quy Tắc Cảnh Báo",
                            SqlTableName = "bnt4_qtcanh",
                            TableNameFull = "quytaccanhbao",
                            TierId = 4
                        },
                        new
                        {
                            Id = 8,
                            Cardinality = "1:N",
                            Description = "Lịch sử cảnh báo đã phát cho bệnh nhân",
                            IsCore = true,
                            Name = "Nhật Ký Cảnh Báo",
                            SqlTableName = "bnt4_nkcbao",
                            TableNameFull = "nhatkycanhbao",
                            TierId = 4
                        },
                        new
                        {
                            Id = 101,
                            Cardinality = "1:N",
                            Description = "Hệ cơ quan sinh học",
                            IsCore = true,
                            Name = "Hệ Cơ Quan",
                            SqlTableName = "bnt5_hecqua",
                            TableNameFull = "hecoquan",
                            TierId = 5
                        },
                        new
                        {
                            Id = 102,
                            Cardinality = "1:N",
                            Description = "Cấu trúc chi tiết cơ quan",
                            IsCore = true,
                            Name = "Cấu Trúc Sinh Học",
                            SqlTableName = "bnt5_cautru",
                            TableNameFull = "cautruc",
                            TierId = 5
                        },
                        new
                        {
                            Id = 103,
                            Cardinality = "1:N",
                            Description = "Chất hoá học hoặc tín hiệu đo lường",
                            IsCore = true,
                            Name = "Chất / Tín Hiệu",
                            SqlTableName = "bnt5_chatin",
                            TableNameFull = "chatinhieu",
                            TierId = 5
                        },
                        new
                        {
                            Id = 104,
                            Cardinality = "1:N",
                            Description = "Danh mục xét nghiệm đo lường",
                            IsCore = true,
                            Name = "DM Xét Nghiệm",
                            SqlTableName = "bnt5_dmxngh",
                            TableNameFull = "dmxnghiem",
                            TierId = 5
                        },
                        new
                        {
                            Id = 105,
                            Cardinality = "1:N",
                            Description = "Reference ranges cho XN",
                            IsCore = true,
                            Name = "Khoảng Tham Chiếu",
                            SqlTableName = "bnt5_ktchie",
                            TableNameFull = "ktchieucu",
                            TierId = 5
                        },
                        new
                        {
                            Id = 106,
                            Cardinality = "1:N",
                            Description = "Y lệnh chỉ định XN",
                            IsCore = true,
                            Name = "Chỉ Định Đo Lường",
                            SqlTableName = "bnt5_ychidi",
                            TableNameFull = "ychidinh",
                            TierId = 5
                        },
                        new
                        {
                            Id = 107,
                            Cardinality = "1:N",
                            Description = "Kết quả đo lường sinh học",
                            IsCore = true,
                            Name = "Kết Quả Đo Lường",
                            SqlTableName = "bnt5_ketqua",
                            TableNameFull = "ketqua",
                            TierId = 5
                        },
                        new
                        {
                            Id = 108,
                            Cardinality = "1:N",
                            Description = "Bối cảnh đo sinh hoá",
                            IsCore = true,
                            Name = "Context Sinh Hoá",
                            SqlTableName = "bnt5_cshoah",
                            TableNameFull = "csinhhoa",
                            TierId = 5
                        },
                        new
                        {
                            Id = 109,
                            Cardinality = "1:N",
                            Description = "Bối cảnh định kỳ của sinh hiệu",
                            IsCore = true,
                            Name = "Context Sinh Hiệu",
                            SqlTableName = "bnt5_cshieu",
                            TableNameFull = "cshieusinh",
                            TierId = 5
                        },
                        new
                        {
                            Id = 110,
                            Cardinality = "1:N",
                            Description = "Bối cảnh tế bào",
                            IsCore = true,
                            Name = "Context Tế Bào",
                            SqlTableName = "bnt5_ctebao",
                            TableNameFull = "ctebao",
                            TierId = 5
                        },
                        new
                        {
                            Id = 111,
                            Cardinality = "1:N",
                            Description = "Bối cảnh hình ảnh",
                            IsCore = true,
                            Name = "Context Hình Ảnh",
                            SqlTableName = "bnt5_hhaanh",
                            TableNameFull = "chinhanh",
                            TierId = 5
                        },
                        new
                        {
                            Id = 112,
                            Cardinality = "1:N",
                            Description = "Bối cảnh điện sinh lý",
                            IsCore = true,
                            Name = "Context Điện Sinh Lý",
                            SqlTableName = "bnt5_dsnlyl",
                            TableNameFull = "diensinhly",
                            TierId = 5
                        },
                        new
                        {
                            Id = 113,
                            Cardinality = "1:N",
                            Description = "Mối liên hệ giữa các xét nghiệm",
                            IsCore = true,
                            Name = "Liên Kết Xét Nghiệm",
                            SqlTableName = "bnt5_xnlqua",
                            TableNameFull = "xnlienquan",
                            TierId = 5
                        },
                        new
                        {
                            Id = 114,
                            Cardinality = "1:N",
                            Description = "Quy tắc cảnh báo XN sinh học",
                            IsCore = true,
                            Name = "Quy Tắc Cảnh Báo XN",
                            SqlTableName = "bnt5_qtcbxn",
                            TableNameFull = "qtcbxn",
                            TierId = 5
                        });
                });

            modelBuilder.Entity("Server.Models.SchemaAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cardinality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("HasPermission")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCore")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SqlColumnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Attributes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cardinality = "1:1",
                            DataType = "VARCHAR(50)",
                            Description = "",
                            GroupId = 1,
                            HasPermission = false,
                            IsCore = true,
                            IsHidden = false,
                            IsRequired = true,
                            Name = "Mã Nhóm",
                            Scope = "System",
                            SqlColumnName = "code"
                        },
                        new
                        {
                            Id = 2,
                            Cardinality = "1:1",
                            DataType = "NVARCHAR(200)",
                            Description = "",
                            GroupId = 1,
                            HasPermission = false,
                            IsCore = true,
                            IsHidden = false,
                            IsRequired = true,
                            Name = "Tên Tiếng Việt",
                            Scope = "System",
                            SqlColumnName = "name_vi"
                        },
                        new
                        {
                            Id = 3,
                            Cardinality = "1:1",
                            DataType = "VARCHAR(50)",
                            Description = "",
                            GroupId = 2,
                            HasPermission = false,
                            IsCore = true,
                            IsHidden = false,
                            IsRequired = true,
                            Name = "Mã Hoạt Chất",
                            Scope = "System",
                            SqlColumnName = "code"
                        },
                        new
                        {
                            Id = 4,
                            Cardinality = "1:1",
                            DataType = "INT",
                            Description = "FK references bnt4_nhomduocly(Id)",
                            GroupId = 2,
                            HasPermission = false,
                            IsCore = true,
                            IsHidden = false,
                            IsRequired = true,
                            Name = "Nhóm Dược Lý ID",
                            Scope = "System",
                            SqlColumnName = "nhomduocly_id"
                        },
                        new
                        {
                            Id = 5,
                            Cardinality = "1:1",
                            DataType = "INT",
                            Description = "FK references bnt4_hoatchat(Id)",
                            GroupId = 5,
                            HasPermission = false,
                            IsCore = true,
                            IsHidden = false,
                            IsRequired = true,
                            Name = "Chất Dị Ứng ID",
                            Scope = "System",
                            SqlColumnName = "hoatchat_id"
                        },
                        new
                        {
                            Id = 6,
                            Cardinality = "1:1",
                            DataType = "INT",
                            Description = "",
                            GroupId = 5,
                            HasPermission = false,
                            IsCore = true,
                            IsHidden = false,
                            IsRequired = true,
                            Name = "Mức độ",
                            Scope = "System",
                            SqlColumnName = "severity"
                        },
                        new
                        {
                            Id = 7,
                            Cardinality = "1:1",
                            DataType = "VARCHAR(20)",
                            Description = "",
                            GroupId = 6,
                            HasPermission = false,
                            IsCore = true,
                            IsHidden = false,
                            IsRequired = true,
                            Name = "Mã ICD",
                            Scope = "System",
                            SqlColumnName = "condition_code"
                        },
                        new
                        {
                            Id = 8,
                            Cardinality = "1:1",
                            DataType = "DATE",
                            Description = "",
                            GroupId = 6,
                            HasPermission = false,
                            IsCore = true,
                            IsHidden = false,
                            IsRequired = false,
                            Name = "Ngày Chẩn Đoán",
                            Scope = "System",
                            SqlColumnName = "diagnosed_at"
                        },
                        new
                        {
                            Id = 101,
                            Cardinality = "1:1",
                            DataType = "VARCHAR(50)",
                            Description = "",
                            GroupId = 101,
                            HasPermission = false,
                            IsCore = true,
                            IsHidden = false,
                            IsRequired = true,
                            Name = "Mã Hệ Cơ Quan",
                            Scope = "System",
                            SqlColumnName = "code"
                        },
                        new
                        {
                            Id = 102,
                            Cardinality = "1:1",
                            DataType = "NVARCHAR(200)",
                            Description = "",
                            GroupId = 101,
                            HasPermission = false,
                            IsCore = true,
                            IsHidden = false,
                            IsRequired = true,
                            Name = "Tên Hệ",
                            Scope = "System",
                            SqlColumnName = "name_vi"
                        },
                        new
                        {
                            Id = 103,
                            Cardinality = "1:1",
                            DataType = "VARCHAR(50)",
                            Description = "",
                            GroupId = 102,
                            HasPermission = false,
                            IsCore = true,
                            IsHidden = false,
                            IsRequired = true,
                            Name = "Mã Cấu Trúc",
                            Scope = "System",
                            SqlColumnName = "code"
                        },
                        new
                        {
                            Id = 104,
                            Cardinality = "1:1",
                            DataType = "INT",
                            Description = "FK references bnt5_hecoquan(Id)",
                            GroupId = 102,
                            HasPermission = false,
                            IsCore = true,
                            IsHidden = false,
                            IsRequired = true,
                            Name = "Hệ Cơ Quan ID",
                            Scope = "System",
                            SqlColumnName = "system_id"
                        },
                        new
                        {
                            Id = 105,
                            Cardinality = "1:1",
                            DataType = "VARCHAR(50)",
                            Description = "",
                            GroupId = 104,
                            HasPermission = false,
                            IsCore = true,
                            IsHidden = false,
                            IsRequired = true,
                            Name = "Mã Xét Nghiệm",
                            Scope = "System",
                            SqlColumnName = "code"
                        },
                        new
                        {
                            Id = 106,
                            Cardinality = "1:1",
                            DataType = "INT",
                            Description = "FK references bnt5_cautruc(Id)",
                            GroupId = 104,
                            HasPermission = false,
                            IsCore = true,
                            IsHidden = false,
                            IsRequired = false,
                            Name = "Cấu Trúc ID",
                            Scope = "System",
                            SqlColumnName = "cautruc_id"
                        },
                        new
                        {
                            Id = 107,
                            Cardinality = "1:1",
                            DataType = "DECIMAL(18,4)",
                            Description = "",
                            GroupId = 107,
                            HasPermission = false,
                            IsCore = true,
                            IsHidden = false,
                            IsRequired = true,
                            Name = "Giá Trị",
                            Scope = "System",
                            SqlColumnName = "result_value"
                        },
                        new
                        {
                            Id = 108,
                            Cardinality = "1:1",
                            DataType = "INT",
                            Description = "FK references bnt5_dmxnghiem(Id)",
                            GroupId = 107,
                            HasPermission = false,
                            IsCore = true,
                            IsHidden = false,
                            IsRequired = true,
                            Name = "Xét Nghiệm ID",
                            Scope = "System",
                            SqlColumnName = "dmxnghiem_id"
                        });
                });

            modelBuilder.Entity("Server.Models.Tier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tiers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Thông tin không thay đổi (Họ tên, ngày sinh, giới tính...)",
                            Name = "Định danh cá nhân",
                            Nature = "Cố định"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Thông tin pháp lý (CMND/CCCD, hộ chiếu...)",
                            Name = "Pháp lý",
                            Nature = "Ít thay đổi"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Thông tin bảo hiểm, thẻ ưu đãi...",
                            Name = "BHYT & Quyền lợi",
                            Nature = "Thay đổi định kỳ"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Gen, nhóm máu, dị ứng bẩm sinh, bệnh nền...",
                            Name = "Di truyền bất biến",
                            Nature = "Bất biến"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Chỉ số sinh tồn, xét nghiệm, kết quả khám...",
                            Name = "Sinh học biến động",
                            Nature = "Biến động liên tục"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Server.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Server.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Server.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Models.Group", b =>
                {
                    b.HasOne("Server.Models.Group", "ParentGroup")
                        .WithMany("SubGroups")
                        .HasForeignKey("ParentGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Server.Models.Tier", "Tier")
                        .WithMany("Groups")
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentGroup");

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("Server.Models.SchemaAttribute", b =>
                {
                    b.HasOne("Server.Models.Group", "Group")
                        .WithMany("Attributes")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Server.Models.Group", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("SubGroups");
                });

            modelBuilder.Entity("Server.Models.Tier", b =>
                {
                    b.Navigation("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
